In [16]:
import numpy as np
def calculate(list):
    if(len(list)!=9):
        raise ValueError("Array can't contain less than 9 integers")

    else:
        arr = np.array(list).reshape(3,3)
        arr_sum = np.sum(arr).tolist()
        print(arr)
        mean_list = [np.mean(arr,axis=0).tolist() , np.mean(arr,axis=1).tolist(),np.mean(arr)]
        print("\nMean :",mean_list)
        var_list = [np.var(arr,axis=0).tolist() , np.var(arr,axis=1).tolist(),np.var(arr)]
        print("\nVariance :",var_list)
        std_list = [np.std(arr,axis=0).tolist() , np.std(arr,axis=1).tolist(),np.std(arr)]
        print("\nStandard deviation :",std_list)
        max_list = [np.max(arr,axis=0).tolist() , np.max(arr,axis=1).tolist(),np.max(arr)]
        print("\nMax :",max_list)
        min_list = [np.min(arr,axis=0).tolist() , np.min(arr,axis=1).tolist(),np.min(arr)]
        print("\nMin :",min_list)
        sum_list = [np.sum(arr, axis=0).tolist(),np.sum(arr, axis=1).tolist(), np.sum(arr)]
        print("\nSum :",sum_list)

calculate([0,1,2,3,4,5,6,7,8])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Mean : [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0]

Variance : [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667]

Standard deviation : [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611]

Max : [[6, 7, 8], [2, 5, 8], 8]

Min : [[0, 1, 2], [0, 3, 6], 0]

Sum : [[9, 12, 15], [3, 12, 21], 36]
